### ISSUE TITLE
Does not compile with nginx 1.11.6

### ISSUE THREAD

**Issue by dyu** [openresty/redis2-nginx-module#41]
Compiled fine with 1.11.5

Error points to the 'default_port' field in https://github.com/openresty/redis2-nginx-module/blob/master/src/ngx_http_redis2_util.c

**Comment by dyu** [comment]
```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../modules/ngx_devel_kit/objs -I objs/addon/ndk -I /data/dyu/dev/bitbucket/devtools/scripts/nginx/target/openssl-1.0.2h/.openssl/include -I objs -I src/http -I src/http/modules -I src/http/v2 -I ../modules/ngx_devel_kit/src -I ../modules/ngx_devel_kit/src -I ../modules/ngx_devel_kit/objs -I objs/addon/ndk \
		-o objs/addon/src/ngx_http_redis2_util.o \
		../modules/redis2-nginx-module/src/ngx_http_redis2_util.c
../modules/redis2-nginx-module/src/ngx_http_redis2_util.c: In function ‘ngx_http_redis2_upstream_add’:
../modules/redis2-nginx-module/src/ngx_http_redis2_util.c:80:21: error: ‘ngx_http_upstream_srv_conf_t {aka struct ngx_http_upstream_srv_conf_s}’ has no member named ‘default_port’
         if (uscfp[i]->default_port
                     ^
../modules/redis2-nginx-module/src/ngx_http_redis2_util.c:82:24: error: ‘ngx_http_upstream_srv_conf_t {aka struct ngx_http_upstream_srv_conf_s}’ has no member named ‘default_port’
             && uscfp[i]->default_port != url->default_port)
                        ^
make[1]: *** [objs/addon/src/ngx_http_redis2_util.o] Error 1

```

**Comment by centminmod** [comment]
yup same issue https://community.centminmod.com/posts/40178/ !

**Comment by Whissi** [comment]
Caused by the following upstream change: http://hg.nginx.org/nginx/rev/4dea01cf49e8

**Comment by Whissi** [comment]
Think we should apply the same fix like http://hg.nginx.org/nginx/rev/3fa5983b6b44

**Comment by agentzh** [comment]
I think this is already fixed in #42.
